### ISSUE TITLE
It does not seam to be loaded

### ISSUE THREAD

**Issue by jb-san** [nragaz/jcrop-rails#1]
I've created a fresh rails 3.1 app, and included gem 'jcrop-rails' in the gemfile. 
I see the /Users/JB/.rvm/gems/ruby-1.9.2-p180@railspre/gems/jcrop-rails-1.0.2/vendor/assets/javascripts
in the Rails.application.config.assets.paths
but I don't see it in /assets/application.js and I can't use the .Jcrop() function
no errors or anything..

anyone know why ?

**Comment by nragaz** [comment]
You need to add `//= require jcrop` to your application.js file along with the other require directives.
