### ISSUE TITLE
Version bump?

### ISSUE THREAD

**Issue by emptyflask** [nragaz/jcrop-rails#6]
Could you increment it so that the newer version of jcrop is used? Right now, the 1.0.2 gem is still using jcrop.js v0.9.9

**Comment by cervelas** [comment]
Yes it would be nice since the deprecated $.browser issue still there. up please.

**Comment by zoer** [comment]
+1. @nragaz, please bump version and update the gem.

**Comment by nragaz** [comment]
Done as 1.0.3. Sorry for the delay.

**Comment by zoer** [comment]
Thanks.
